### PR TITLE
I am happy

### PR DESCRIPTION
**Pull request by ismoil5444**
we are zed team we are legion we are do

### CODE REVIEW

**Comment by ismoil5444** [comment]
we are zed team we are legion we do mot forget we do not forgive expect us
@Abror2110

**Comment by lazizb** [comment]
qonady

**Comment by ismoil5444** [comment]
> 
zorkooo

**Comment by lazizb** [comment]
you are happy or sad

**Comment by JohoN-1231** [comment]
qonday bosa shunday

**Comment by lazizb** [comment]
> 
malads

**Comment by JohoN-1231** [comment]
axa  raxmat bratuxa

**Comment by ismoil5444** [comment]
> 

im happy @lazizb

**Comment by JohoN-1231** [comment]
were  god!

**Comment by ismoil5444** [comment]
nma qvoslaaaaaa @lazizb @JohoN-1231

**Comment by JohoN-1231** [comment]
@ismoil5444 maza qivomiz

**Comment by JohoN-1231** [comment]
5x1

**Comment by lazizb** [comment]
kayp

**Comment by JohoN-1231** [comment]
vashe

**Comment by lazizb** [comment]
ozinchi

**Comment by ismoil5444** [comment]
> @ismoil5444 maza qivomiz

mazzami slaga yonmayon otrb yozishish @lazizb @JohoN-1231

**Comment by JohoN-1231** [comment]
+?

**Comment by JohoN-1231** [comment]
@ismoil5444   yo mazamas    vawe kayfuem!!

**Comment by lazizb** [comment]
> > @ismoil5444 maza qivomiz
> 
> mazzami slaga yonmayon otrb yozishish @lazizb @JohoN-1231
biza maqtanvommiiz
ismoil 19

**Comment by ismoil5444** [comment]
> 

otrimma man @lazizb

**Comment by JohoN-1231** [comment]
@ismoil5444 solo  protiv skvad

**Comment by JohoN-1231** [comment]
yo yo yo duo

**Comment by ismoil5444** [comment]
> @ismoil5444 solo protiv skvad

uxx lobbi bomi akalaaa

**Comment by JohoN-1231** [comment]
bor prosta telda yo oyin

**Comment by ismoil5444** [comment]
> bor prosta telda yo oyin

iye axaxax nmada oynisan pubg

**Comment by JohoN-1231** [comment]
da

**Comment by JohoN-1231** [comment]
iye    shottaya pubg imgimi?

**Comment by ismoil5444** [comment]
> 

qachoon e lobbi oynimz

**Pull request merged**
